version: '3'

services:
  proviant:
    container_name: "proviant-compose"
    image: brushknight/proviant:0.0.20
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - 8080:80
    dns:
      - 8.8.8.8
    restart: unless-stopped

  mariadb:
    container_name: "proviant-mariadb"
    image: mariadb
    restart: unless-stopped
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "proviant"
      MYSQL_ROOT_PASSWORD: "111111"
    ports:
      - 3306:3306

volumes:
  mysql:
    driver: local
    driver_opts:
      type: none
      device: $PWD/db/mysql
      o: bind
