version: '3'

services:
  proviant:
    container_name: "proviant-core"
    image: brushknight/proviant-core:dev
    volumes:
    - ./examples/config/web-mysql-gcs.yml:/app/default-config.yml
    - ./gcs-secret.json:/app/gcs-secret.json
    - user_content:/app/user_content
    links:
      - mariadb:db
    depends_on:
      - mariadb
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - 8080:80
    dns:
      - 8.8.8.8
    restart: unless-stopped

  mariadb:
    container_name: "proviant-mariadb"
    image: mariadb
    restart: unless-stopped
    volumes:
      - mysql:/var/lib/mysql
    ports:
    - 3307:3306
    environment:
      MYSQL_DATABASE: "proviant"
      MYSQL_ROOT_PASSWORD: "proviant"

  pma:
    container_name: "proviant-pma"
    image: phpmyadmin/phpmyadmin
    links:
      - mariadb:mariadb
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: "proviant"
    ports:
      - 8082:80
    restart: always

volumes:
  mysql:
    driver: local
    driver_opts:
      type: none
      device: $VOLUMES_PREFIX/mysql
      o: bind

  user_content:
    driver: local
    driver_opts:
      type: none
      device: $VOLUMES_PREFIX/user_content
      o: bind