name: Test on each push

on:
  push:
    branches:
      - '**'

env:
  DOCKER_HUB_ID: brushknight
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

jobs:
  test-container:
    name: Build container
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_HUB_ID }}
          password: ${{ env.DOCKER_HUB_PASSWORD }}
      - run: touch envfile
      - run: make docker/build

  test-e2e:
    name: Run e2e tests
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.5
      - run: touch envfile
      - run: make test/e2e

  test-unit:
    name: Run unit tests
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.5
      - run: touch envfile
      - run: make test/unit