name: Test on each push

on:
  push:
    branches:
      - '**'

jobs:
  test-e2e:
    name: Run e2e tests
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.5
      - run: touch envfile
      - run: make test/e2e

  test-unit:
    name: Run unit tests
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.5
      - run: touch envfile
      - run: make test/unit