name: Release docker image with latest proviant version

on:
  release:
    types:
      - released
    tags:
      - '*'

env:
  TAG: ${{ github.event.release.tag_name }}
  DOCKER_HUB_ID: brushknight
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

jobs:

  test-e2e:
    name: Run e2e tests
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.5
      - run: make test/e2e

  docker:
    name: Publish docker image
    runs-on: ubuntu-20.04
    needs: [test-e2e]

    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_HUB_ID }}
          password: ${{ env.DOCKER_HUB_PASSWORD }}
      - run: make docker/build
      - run: make docker/publish